all: oppgave1 oppgave2

oppgave1: oppgave1.c
	 gcc -o oppgave1 oppgave1.c

oppgave2: oppgave2.c
	 gcc -o oppgave2 oppgave2.c

run1: oppgave1
	 ./oppgave1

run2: oppgave2
	 ./oppgave2

clean: 
	 rm -f oppgave1 oppgave2